FROM python:3.10

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ${ROOT_PROJECT} .

ENV FLASK_APP=run:app
ENV FLASK_ENV=development

EXPOSE 5050

CMD ["flask", "run", "--host=0.0.0.0", "--port=5050"]