"""empty message

Revision ID: 1f1be55375b0
Revises: 6af13f67c25a
Create Date: 2025-03-10 00:41:59.329283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1be55375b0'
down_revision = '6af13f67c25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_anonymisations')
    with op.batch_alter_table('anonymisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_anonym_group', 'group_users', ['group_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anonymisations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_anonym_group', type_='foreignkey')
        batch_op.drop_column('group_id')

    op.create_table('_alembic_tmp_anonymisations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('footprint_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('shuffled_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('original_file', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_link', sa.VARCHAR(length=255), nullable=False),
    sa.Column('naive_attack', sa.FLOAT(), nullable=False),
    sa.Column('utility', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_users.id'], name='fk_anonym_group', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_link'),
    sa.UniqueConstraint('footprint_file'),
    sa.UniqueConstraint('shuffled_file')
    )
    # ### end Alembic commands ###
