"""empty message

Revision ID: 6af13f67c25a
Revises: c940cea42e4e
Create Date: 2025-03-09 18:06:43.102957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af13f67c25a'
down_revision = 'c940cea42e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anonymisations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anonymisations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
