"""empty message

Revision ID: 6b000a5ac05e
Revises: 3d0df482e1e5
Create Date: 2025-03-09 14:32:14.993273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b000a5ac05e'
down_revision = '3d0df482e1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.alter_column('parameters',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.alter_column('parameters',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
