"""Added AttackModel

Revision ID: a9a21a6138af
Revises: 1f1be55375b0
Create Date: 2025-03-14 00:07:09.474803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a21a6138af'
down_revision = '1f1be55375b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('anonym_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anonym_id'], ['anonymisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['group_users.id'], name='fk_attack_group', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attacks')
    # ### end Alembic commands ###
