"""empty message

Revision ID: c940cea42e4e
Revises: 6b000a5ac05e
Create Date: 2025-03-09 14:44:33.642566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c940cea42e4e'
down_revision = '6b000a5ac05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.alter_column('parameters',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.alter_column('parameters',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
